### ISSUE TITLE
[Enhancement] Manage automatic dependency updates with automatic pipeline check

### ISSUE THREAD

**Issue by RobbenRiksen** [shapeshifter/shapeshifter-specification#113]
## **Describe the improvement**
A clear and concise description of what the suggestion is.

## **Expected behavior**
A clear and concise description of what you expected to see.

## **Screenshots**
If applicable, add screenshots to help explain your suggestion.

**Additional context**
Add any other context about the suggestion here.

**Comment by RobbenRiksen** [comment]
Nico will have look

**Comment by nicorikken** [comment]
Pipeline is in place. Some PR's were from before Dependabot.
