### ISSUE TITLE
FlexSettlementType is derived from PayloadMessageResponseType

### ISSUE THREAD

**Issue by radboudp** [shapeshifter/shapeshifter-specification#25]
**Describe the bug**
FlexSettlementType extends PayloadMessageResponseType. However, it is not a response and should not have the Result and RejectionReason fields. 

**To Reproduce**
See UFTP-agr-dso.xsd line 450

**Expected behavior**
FlexSettlementType should extends PayloadMessageType

**Comment by tomwetjens** [comment]
Duplicates #53
