### ISSUE TITLE
Documentation Paragraph 3.5 "Invalid Message" unclear

### ISSUE THREAD

**Issue by radboudp** [shapeshifter/shapeshifter-specification#30]
Documentation should be more specific what is to be validated.
Currently it reads as "validations required by implementation", but these kind of validations are mentioned by each specific message types validations as: "Any other reasonable cause to reject the message" with reason "[User defined]".

**Comment by tomwetjens** [comment]
Currently the 3.0.0 spec reads:
Invalid Sender
Despite being schema-compliant, the syntax, type or semantics of the message were unacceptable for the receiving implementation.

Invalid Message
There is a mismatch between the SenderDomain/Role combination in the message wrapper and the inner XML message.

They should be swapped.

Also SenderDomain/Role combination is not on the inner message, but only on the wrapper (SignedMessage).


Add to the spec that custom validations may be added in addition to these mentioned in the spec. They may use their own rejection reasons.

**Comment by capacious** [comment]
Fixed in doc_update commit

**Comment by capacious** [comment]
Fixed in [PR !87](https://github.com/shapeshifter/shapeshifter-specification/pull/87)
