### ISSUE TITLE
Documentation paragraph 3.5 "Unknown reference" unclear

### ISSUE THREAD

**Issue by radboudp** [shapeshifter/shapeshifter-specification#36]
The documentation should list in the description of the validation which message types specify one or more references that should be validated. 
The documentation should list per message type which fields are references that should be validated.
The documentation should clearly specify per message type field that holds a reference, to which field of which message type it refers in order to implement the validation.

**Comment by tomwetjens** [comment]
Add to specification which rejection reasons are applicable to which messages.

**Comment by capacious** [comment]
Fixed in [PR !87](https://github.com/shapeshifter/shapeshifter-specification/pull/87)
