### ISSUE TITLE
Documentation paragraph 3.5 "ISPs out of bounds" unclear

### ISSUE THREAD

**Issue by radboudp** [shapeshifter/shapeshifter-specification#43]
Should list the messages that need to be validated.
Should list which elements or sub elements of those messages contain ISP lists to be checked.
Should clarify how to determine the number of ISPs per day, also for winter/summer time transition days.
Should clarify how to determine winter/summer time transition days at origin of the message (time zone issues).

**Comment by capacious** [comment]
Need to check if the summer- wintertime stuff needs to be clarified further

**Comment by capacious** [comment]
Fixed in [PR !87](https://github.com/shapeshifter/shapeshifter-specification/pull/87)
