### ISSUE TITLE
Documentation paragraph 3.5 "Period out of bounds " unclear

### ISSUE THREAD

**Issue by radboudp** [shapeshifter/shapeshifter-specification#45]
Should list which messages to validate.
Should clarify per message which field needs to be validated against what other fields or times.

**Comment by tomwetjens** [comment]
There are some generic rules per message type. Like in case of FlexRequest 'cannot be in the past'
 Some are specific to country or implementation and cannot be part of the spec. E.g. FlexRequest for 'day ahead' must be in the future, but not more than 1 day'

**Comment by capacious** [comment]
Added the generic rules to the doc_update MR, agree with Tom that some are too specific for the different usecases

**Comment by capacious** [comment]
Fixed in [PR !87](https://github.com/shapeshifter/shapeshifter-specification/pull/87)
