### ISSUE TITLE
Documentation paragraph 3.5 "ExpirationDateTime out of bounds " unclear

### ISSUE THREAD

**Issue by radboudp** [shapeshifter/shapeshifter-specification#46]
Should list which messages to check the expiration date time for.
Should clarify per message what values the expiration date time needs to adhere to.

**Comment by capacious** [comment]
Proposed a solution in the doc_update MR

**Comment by capacious** [comment]
Fixed in [PR !87](https://github.com/shapeshifter/shapeshifter-specification/pull/87)
