### ISSUE TITLE
Documentation paragraph 3.5 "Unknown Recipient" unclear

### ISSUE THREAD

**Issue by radboudp** [shapeshifter/shapeshifter-specification#49]
The current description reads as:
```
The RecipientDomain and/or RecipientRole specified in the inner XML message is not handled by this endpoint
```

However, the XSD does not specify any recipient ROLE in the PayloadMessageType.

Documentation (or XSD) should be updated. The documentation should specify what is to be validated. For example: 

```UFTP Domain of the party/application receiving the message must match the recipient domain inside the inner XML.```

**Comment by capacious** [comment]
---Proposed change RS/DW---
There are two cases:
* "SenderDomain Unknown": A message is received containing a SignedMessage\SenderDomain that's not known to, or connot be resolved by the recipient
* "SenderDomain Mismatch": SignedMessage\SenderDomain doesn't match SignedMessage\Body\SenderDomain

So we propose to add an additional Message validation entry to clarify both cases

**Comment by capacious** [comment]
Committed to branch doc_update

**Comment by capacious** [comment]
Fixed in [PR !87](https://github.com/shapeshifter/shapeshifter-specification/pull/87)
