### ISSUE TITLE
CMS for documentation

### ISSUE THREAD

**Issue by radboudp** [shapeshifter/shapeshifter-specification#56]
The PDF documentation is old fashioned and difficult to make references in. By moving the documentation to an internet page we can make a layered documentation that can have references and can be indexed by Google.

My suggestion is to create a CMS (for example WordPress) in which the documentation can be setup and can be served by. Wiki is also an option. Or MD, although I feel we have the need for more advanced features that MD and wiki might not provide.

I'll investigate if GOPACS is willing to server the CMS.

**Comment by nicorikken** [comment]
Agreed, the current Word document which only opens in LibreOffice is far from ideal.

A CMS can be an interesting option but is quite uncommon. Most specs project I see use a text-based format like Markdown to write documentation and use some generator to build a static website and possibly other outputs like a pdf version.

With a text-based source format the **GitHub process of pull requests** can be used. This has the benefit of:
- scaling to many contributions
- being open to outside contributions

Thinking about the **use-case** at Shapeshifter these concerns came to mind:
- Primary method of access will be through the website
- Pdf download must be available for reference and sharing
- Editing must be accessible to less technical users, locally and online through the GitHub UI
- Ideally multiple versions should be available for viewing 
- Generation and website publication should be automatic
- Integrating or linking to API documentation could be a nice addition

### PDF generation
There are 3 main solutions in use for generating pdf documents from text formats:

- **LaTeX** Somehow generate LaTeX and renders that to pdf. Goodlooking but it requires tweaking to match the existing look or the look from the website.
- **Website render** Render the website as a pdf, similar to how you would print a website. Can be done by spinning up a headless webbrowser or by calling [pdf.js](https://mozilla.github.io/pdf.js/)
- **[Weasyprint](https://weasyprint.org/)** which renders a pdf based on HTML format in a more direct way with more control over the output.

### Hugo + Docsy theme
Looking for **solutions** that match the extensiveness of the Shapeshifter the Kubernetes documentation ([Website](https://kubernetes.io/docs/home/), [Git](https://github.com/kubernetes/website/tree/main/content/en/docs)) came to mind. Kubernetes uses [Hugo](https://gohugo.io) as static site generator with the [Docsy](https://www.docsy.dev/docs/) theme. This setup is also used by the [OpenChain Korean Working Group](https://openchain-project.github.io/OpenChain-KWG/en/resource/) Docsy has a print feature where it generates a single-page view of a section which makes it easier to print.

_This setup is well maintained but lacks quality pdf rendering._

### Mkdocs + mkdocs-material
[Mkdocs](https://www.mkdocs.org/) is specifically popular for generating documentation, especially in the Python community. Pdf generation is possible using the mkdocs-material theme and a [pdf-plugin](https://isolveit.github.io/mkdocs-pdf-generate/options/) (example [pdf](https://isolveit.github.io/mkdocs-pdf-generate/options/Plugin_Options.pdf). This pdf is based on the Weasy and looks good and consistent with the website.

_This setup is a bit more gobbled together but is able to produce neat PDF documents._

### Refspec template
Dutch Logius organization has done some work to instrument the Refspec template used by the W3C standards body, make it accept Markdown files and add the option to render pdf files from it using pdf.js. The code is available here: https://github.com/Logius-standaarden/ReSpec-template/ and an example document is here https://logius-standaarden.github.io/ReSpec-template/: 

_This setup works well, but has a very specific look and the documentation is mainly in Dutch.

I'm looking for feedback, best practices and other suggestions. Then we can pick an approach at the TSC meeting and move towards a trial.

**Comment by RobbenRiksen** [comment]
Resolved by pull request https://github.com/shapeshifter/shapeshifter-specification/pull/67 and the great contribution of @nicorikken
