### ISSUE TITLE
Allow multiple congestion points per connection

### ISSUE THREAD

**Issue by Edward-Ross-Gridimp** [shapeshifter/shapeshifter-specification#66]
<h1>1.1 Describe the improvement</h1>
The improvement would consist of allowing one connection identifier to be linked to multiple congestion points. Currently, the protocol only allows a connection identifier to be connected to a single congestion point in the Common Reference. This is identified as a reason for rejection of a connection registration in section 3.6.1 of the USEF Flex Trading Protocol Specifications 3.0.0.
This limitation does not allow to reflect the potential impact of a connection in different congestion points (or for different grid configurations), limiting the potential use of a connection to solve different congestion problems.

<h1>1.2 Additional context</h1>
This change request was initiated by Project FUSION since this problem was encountered during the trial.

<h1>1.3 Expected [behavior</h1>
What is expected is that the DSO has the freedom to define link the connection to different congestion points in the Common Reference.

[Change request - allow multiple CPs per connection.pdf](https://github.com/shapeshifter/shapeshifter-specification/files/10547727/Change.request.-.allow.multiple.CPs.per.connection.pdf)

**Comment by Edward-Ross-Gridimp** [comment]
This change request was approved by the TSC on 30/01/2023

**Comment by RobbenRiksen** [comment]
Merged https://github.com/shapeshifter/shapeshifter-specification/pull/70 to fix this issue
